### ISSUE TITLE
[Lecture05][0420] Ransac and homography

### ISSUE THREAD

**Issue by nshuhsn** [PiLab-CAU/ComputerVision-2401#20]
When we calculate H in Ransac, we set h22 = 1 because it is used to maintain 1 in translation movement. So my question is why h20 and h21 is not zero? We don't need h20 and h21 in Scaling, Rotation, Translation, so in lecture 2 we set h20 and h21 as zero.
Are there any reasons we cannot set h20 and h21 as zero?

**Comment by yjyoo3312** [comment]
@nshuhsn Thank you for highlighting this important issue!

I believe this graph will help explain why we chose h20 and h21 as parameters to estimate.

<img width="631" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/af8560dc-00cf-40b8-8fac-c602b81c0589">

When h20 and h21 are zero, the transformation is known as an Affine transformation, which involves scaling, rotation, and translation. By setting h20 and h21 as parameters, we can represent a wider variety of transformations, which are then referred to as perspective transforms.

Often, deriving the perspective transform matrix is beyond the scope of an undergraduate computer vision course, so I only cover up to affine transformations.

Exploring the derivation of the perspective form would be an excellent study topic. However, for the purpose of our class, it's sufficient to understand that we can represent various transformations using the eight transformation matrix parameters (only excluding h22), known as perspective transform, which can be estimated using four point-pairs.

Also, in our class, the decomposition of the transformation matrix (for example, scale, rotation, and translation) will be limited to the affine transformation case since we did not deal with the case other than the affine transformation.
