### ISSUE TITLE
[lecture10][0605] 3x3 kernels in AlexNet

### ISSUE THREAD

**Issue by koallako** [PiLab-CAU/ComputerVision-2401#34]
![IMG_1471](https://github.com/PiLab-CAU/ComputerVision-2401/assets/162315413/d772db6c-8387-4bb0-9105-c0058d8b9f39)

I'm curious about why AlexNet use a 3x3 convolution corresponding to the red range that I checked on the image. Also, why is the last convolution of that part has fewer filters than the previous two convolutions? (384>256)

Minjung Kim

**Comment by HJH0303** [comment]
In my opinion, it is for dimensionality reduction to reduce model complexity. Or maybe because 384 is not a power of 2, it was reduced for computational efficiency.

**Comment by koallako** [comment]
Thanks for your opinion! But I still got curious. In these convolutions, does the number of filters that are powers of 2 matter? Then, why did the first convolution (11x11) use 96 filters?

**Comment by HJH0303** [comment]
CPU and GPU memory architectures are organized in powers of 2 (0 or 1). Using powers of 2 is beneficial because it optimizes memory allocation and enhances hardware efficiency on CPUs or GPUs. However, I think that filter sizes or counts are sometimes not powers of 2 due to design decisions based on empirical performance. For example, ResNet uses a 7x7 filter size and 64 filters in its stem layer. Additionally, according to Nvidia's official website, tensor matrices are more efficient when their size is a power of 8 or 16. 
![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/89338327/96c7d71b-0fa5-4db8-9f6f-aed2babd40ae)
[Table 1. Link](https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc)

**Comment by yjyoo3312** [comment]
@koallako @HJH0303 Thank you for the comment and discussion! It was interesting to read.

@koallako Since I am not Alex, the original author, it's challenging to speculate on the reason. In my view, it might be associated with reducing the computational burden required in the (Flattening -> FC layer -> FC layer -> FC layer) section, which is computationally intensive. In the AlexNet paper, they employed a clever implementation leveraging two GPUs to address the insufficient GPU memory size at that time (However, in terms of parallelism, it was pioneering attempt)

@HJH0303 As you mentioned, setting the channel size to a power of 2 is preferable. However, AlexNet already employed a 384-size (and 96) channel for convolutions in their architecture. Considering that the authors implemented the GPU operations required for the Conv operation from scratch (as they could not use CuDNN, of course), I believe they reduced the channel size to 256 due to limitations imposed by the GPU they used.

An important point to note is that the AlexNet architecture was pioneering, although from our current perspective, some of its designs may not be considered efficient, especially considering it's been 20 years since its inception. It would be intriguing to examine how these design elements have evolved into more effective ones in subsequent architectures:)
