### ISSUE TITLE
[lecture13][0608] Faster R-CNN: TradeOff between number of anchor boxes and FPS

### ISSUE THREAD

**Issue by jeonghyunpark2002** [PiLab-CAU/ComputerVision-2401#38]
Hi professor!

I have question about setting number of anchor boxes.

By default, we set it as 9 in usual case.

However, If we set it to lower value, I can expect more FPS without losing performance loss. 

Is there any research or results about adjusting this value??

Thank you!

**Comment by yjyoo3312** [comment]
@jeonghyunpark2002 

Indeed, varying the number of anchor boxes can impact detection performance. For instance, removing horizontally long anchor boxes would likely degrade performance as we cannot detect horizontally long objects.

Using fewer anchor boxes does indeed speed up inference time, primarily by reducing the processing time in the Non-Maximal Suppression step.

Since the number of anchor boxes can affect detection performance, we usually use them as fixed hyper-parameters for fair comparison. About adjusting anchor boxes, paper like this one, [Soft Anchor-Point Object Detection](https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123540086.pdf), would be helpful to start.

**Comment by jeonghyunpark2002** [comment]
Thank you for resolving my question and providing paper to study further :)

**Comment by yjyoo3312** [comment]
@jeonghyunpark2002 Regarding this, I heard that [YOLOv10](https://arxiv.org/abs/2405.14458) offers non-maximum suppression (NMS) free detection (though I haven't read up on it yet). If you're keen on enhancing the post-processing aspect of detectors, It would be nice to check YOLOv10 details.
