### ISSUE TITLE
[lecture11][0610] About CutMix or Cutout

### ISSUE THREAD

**Issue by HJH0303** [PiLab-CAU/ComputerVision-2401#40]
In the lecture, @yjyoo3312 explained that random cropping of images may exclude object regions, which can decrease accuracy.
![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/89338327/3a880ca9-dab6-4982-a305-d52cd43bc2e6)

However, I think the Cut-Mix or Cut-Out also excludes object regions, as shown in the image below. If the object region is small, the Cut-Out randomly cuts a patch that might contain the object region. Cut-Mix has a similar issue as Cut-Out. Is it necessary to additionally annotate where the object is and its size to avoid excluding the object region?
![cut_out](https://github.com/PiLab-CAU/ComputerVision-2401/assets/89338327/0d2a26af-75b3-467c-ae56-3c046f67922e)

**Comment by yjyoo3312** [comment]
@HJH0303 Thank you for the comment!

As you mentioned, Cutout and Cutmix techniques can also unintentionally exclude objects crucial for classification in an image. To address this issue, some approaches have been proposed to control the region that is mixed or removed, utilizing attention or saliency.

- https://arxiv.org/pdf/2003.13048
- https://arxiv.org/abs/2006.01791

In my opinion, incorporating attention or saliency into data augmentation might be excessive due to the computational burden, especially considering the performance gains it offers.

We still do not clearly understand the performance improvement factors of such augmentations Cutmix, so if you have any good ideas, please contact me:)

**Comment by HJH0303** [comment]
Thank you for your answer :)

**Comment by HJH0303** [comment]
Thank you for your answer :) There are already papers that's been considered for my opinion.

**Comment by HJH0303** [comment]
@yjyoo3312 Partcipation score has not changed for this issue #40. Thank you :)

**Comment by yjyoo3312** [comment]
@HJH0303 Oh, I omitted it, Thank you for letting me know:)
