### ISSUE TITLE
[lecture12][0614] Inquiry Regarding "Black Dog at Center" Classified as False Negative

### ISSUE THREAD

**Issue by zxcv3296** [PiLab-CAU/ComputerVision-2401#48]
![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92920482/ed702392-cf34-45da-9e58-440e8836fdb6)

I am writing to inquire about the specific reason why the "Black dog at Center" example on page 34 of our lecture slides is classified as a false negative.

Could you please clarify the following points regarding this classification?

Thank you.

**Comment by yjyoo3312** [comment]
@zxcv3296 Thank you for the comment!

Let's see the Black dog at center. Since we cannot predict the Box, it is Negative (If you predict the box there, it is positive).
And this negative prediction is False, so it is False Positive.

Note that Prediction box 2,3 are Positive (Since we at least predict the box) but False, becuase of low IOU.
