### ISSUE TITLE
[Lecture3][0321]Questions about LoG, DoG

### ISSUE THREAD

**Issue by choigiheon** [PiLab-CAU/ComputerVision-2401#5]
@yjyoo3312, I have two questions about Laplacian of Gaussian (LoG)!

<img width="700" alt="Screenshot 2024-03-21 at 13 47 07" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/118817112/c989041d-4603-474b-9fd7-db19883432e7">

1) When using LoG, if edge detection is based on zero-crossings, how do we differentiate between case 1 and case 2 in Figure, which are both zero-crossing but one is on edge and the other is not?

2) I heard that the reason for approximating LoG with DoG is due to computational complexity. However, since convolutional filters are fixed in advance, it doesn't seem necessary to worry about computation. Are there cases where LoG is computed multiple times?

Thank you very much!

**Comment by yjyoo3312** [comment]
@choigiheon 
(just call me @yjyoo3312 in this repo:) )
Thank you for the constructive questions!

1. Addressing the first issue, we can examine neighboring pixels around zero crossings to provide a solution. While not perfect (yet quick and accurate in most cases), the example convolutional kernel could be considered, as:

```
filter = np.array([
    [1, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])
```


2. The Difference of Gaussians (DoG) is broadly utilized because keeping a collection of Gaussian-blurred images, known as a Gaussian Pyramid, is a standard practice in Computer Vision for a diverse range of applications, 
 https://github.com/PiLab-CAU/ComputerVision-2401/blob/5ca29bcaa331732d9ac8bb3ee6b91318f623665c/lecture4/example_SIFT_HoG.py#L23
such as super resolution, and keypoint detection. It is because this technique is employed to capture images across multiple scales . Often, as illustrated in the reference below, the pyramid of images subtracting two different level is referred to as a Laplacian pyramid, although it is not precisely the same as a Laplacian of Gaussian.
To summarize, in numerous computer vision applications, we typically maintain a pyramid of images blurred at varying levels. By subtracting these images, we obtain an approximation of Laplacian of Gaussian (LoG) images, rather than applying the exact Laplacian kernel directly.
- The term 'Laplacian pyramid' is often used to describe the structure resulting from the subtraction of two images that have been smoothed differently, especially when these images are subsequently downsampled and rescaled. (It's important to note that this subtraction process approximates the LoG operation.)
- The term 'DoG pyramid' is used when referring to a pyramid where each level results from subtracting two images that have undergone Gaussian smoothing with different sigma values.
- Of course, both terms, in many case, are used without clear distinction in our field, like convolution and correlation :)


[References] 
https://arxiv.org/pdf/1506.05751v1.pdf <- this one is a classical GAN paper, applying the Laplacian Pyramid.
https://sepwww.stanford.edu/data/media/public/sep/morgan/texturematch/paper_html/node3.html

**Comment by choigiheon** [comment]
I think I roughly understand, but I'm not sure.
Is the reason for not directly applying the LoG filter and instead subtracting two different Gaussian-blurred images because the collection of Gaussian-blurred images is used for a different purpose other than LoG?

**Comment by yjyoo3312** [comment]
Yepp, indeed. 
Since creating a Gaussian image pyramid is a common practice for various computer vision applications, subtraction is an efficient choice to obtain a LoG image for those cases. Nonetheless, when the task requires applying a LoG operation to an image directly, utilizing a LoG kernel also serves as a good alternative.

**Comment by choigiheon** [comment]
Ok, I got it! Thank you for answering!!! :D
