### ISSUE TITLE
[Lecture9][0616] Degree to reduce the parameters of depthwise/pointwise convolution

### ISSUE THREAD

**Issue by kimjyan20221186** [PiLab-CAU/ComputerVision-2401#50]
Hello, professor @yjyoo3312. I understand that both the pointwise convolution and the depthwise convolution can reduce the parameters because they reduce the dimensions. So, are the two convolutions different in the degree to which they reduce the parameters?
-Kim JiHyeon

**Comment by yjyoo3312** [comment]
@kimjyan20221186 Thank you for the comment!

Both types of convolutions reduce parameter size, but they serve different purposes.

We refer to pointwise convolution as having a kernel size of (1x1). When configured equivalently in terms of input and output channels as standard 3x3 convolution, it reduces convolution parameters to 1/9. However, while it mixes input channels, it does not integrate spatial features because it only considers a single point.

Depthwise convolution, on the other hand, operates with a group size equal to the input channel size, significantly reducing parameter size (by how much?). It blends spatial features but does not mix input channels, unlike pointwise convolution.

Therefore, we employ both pointwise and depthwise convolutions to replace standard convolution.

**Comment by kimjyan20221186** [comment]
@yjyoo3312 Thank you for your reply. Then can the depthwise convolution reduce the number of parameters more significantly than the pointwise convolution?

**Comment by yjyoo3312** [comment]
@kimjyan20221186  Yepp, group convolution reduces the number of parameters in proportion to the number of groups (important!). So, Depthwise convolution can reduce the number of parameters more significantly than pointwise convolution in most cases.

**Comment by kimjyan20221186** [comment]
@yjyoo3312 Thank you, it helped me a lot to understand!
