### ISSUE TITLE
[Lecture12][0617] NMS: What if objects are overlapped?

### ISSUE THREAD

**Issue by StevenHSKim** [PiLab-CAU/ComputerVision-2401#52]
<img width="995" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/102468317/5490265a-f85f-406e-9249-eeb79d9133ac">

In the example above, the two cars are not overlapping each other in the image. Therefore, if we perform NMS, we can have (0.9, 0.8) bounding boxes, one for each object.

But suppose we have an image where two cars are overlapped, and we perform NMS between them. If only one car has a bounding box due to the IoU threshold, is this the correct way to perform NMS?

Thank you!
HaeSung Kim

**Comment by yjyoo3312** [comment]
@StevenHSKim Thank you for the comment!

Let's see the pseudo code from (https://arxiv.org/pdf/1704.04503) -> ignore the soft-nms part.
<img width="439" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/43c31c12-82d9-49f8-bfaa-348079c978be">

Except for the sorting part (where they use the argmax of confidence instead of sorting), we can see that NMS works the same as in our example (class-wise). 

As you mentioned, when two identical objects are highly overlapped, it becomes difficult to detect the overlapped one, which is a typical problem. Actually, to address this problem, the soft-NMS method has been proposed, as referenced in the link above. If you have a time, it would be nice to read the paper.
