### ISSUE TITLE
[Lecture13][0617] About feature upscaling

### ISSUE THREAD

**Issue by jwemilee** [PiLab-CAU/ComputerVision-2401#54]
Hello,

I have a question regarding the upsampling feature map:

I understand that Bilinear Upsample + Convolution is computationally efficient, while ConvTranspose2D can generate more precise and detailed feature maps. Given these differences, is the choice of ConvTranspose2D in deconvolution network mainly to enhance the precision and detail of the upsampled features for better segmentation performance?

Additionally, could you explain why ResNet101 was chosen as the backbone network for DSSD? What benefits does ResNet101 provide?

Thank you!

**Comment by yjyoo3312** [comment]
@jwemilee Thank you for the comment!

In my opinion, it is difficult to say that ConvTranspose2D (also known as deconvolution) is better than upsampling followed by convolution. Many segmentation and generation architectures, such as DeepLabv3 and BigGAN, use upsampling instead of ConvTranspose2D and still achieve near state-of-the-art performance in their respective domains. Additionally, ConvTranspose2D can cause issues like [checkerboard artifacts](https://distill.pub/2016/deconv-checkerboard/), making upsampling followed by convolution a more widely used option for expanding input feature maps, especially in generation task.

The first property is that ResNet 101 has higher ImageNet classification accuracy, which suggests better transferability, although this is not guaranteed in all cases. Additionally, using ResNet 101 can increase the overall depth of the feature map used for detection, providing the feature map with more high-level information about images.
