### ISSUE TITLE
Lecture11 Balancing image combination ratios for enhanced performance

### ISSUE THREAD

**Issue by junehyeok129** [PiLab-CAU/ComputerVision-2401#61]
I understood that Cutmix's principle is to combine the two pictures and do the labeling in this way [0.5, 0.5]. However, if you combine the two pictures like [0.9,0.1] or [0.95,0.05], the performance is expected to be lower. How did you solve this problem? Or is there an optimal range?

**Comment by yonghyun010102** [comment]
I believe this is related to using the beta function in probability sampling.

![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92546000/72bd41b1-6421-4b63-90cd-9aac40e9abbc)


As illustrated, by setting hyperparameters, we can set the probability density function to be lower at the extremes, such as near 0 or 1. This helps in adjusting so that extreme values like 0.95 or 0.1 are less likely to be sampled. Additionally, by tuning the hyperparameters of the beta function, it is possible to empirically determine the optimal hyperparameters for sampling probabilities.

@yjyoo3312 Could you please confirm if my understanding is correct? Thank you!

**Comment by yjyoo3312** [comment]
@junehyeok129 @imsongpasimin Thank you for the comment and the correct answer.

By adjusting the hyperparameters of the Beta distribution, we can control the mixing ratio of two images (@imsongpasimin).

It's important to note that even if the mixing ratio between class 0 (represented as [1, 0]) and class 1 (represented as [0, 1]) is skewed towards one class, such as [0.9, 0.1] or [0.05, 0.95], it does not pose a significant issue because the labels are smoothed to the same ratio. For instance, in the case of a [0.05, 0.95] mixing ratio, we use the smoothed label [0.05, 0.95].
