### ISSUE TITLE
[lecture9-2] [0619] Inquiry on Parameter Reduction in CNNs

### ISSUE THREAD

**Issue by zxcv3296** [PiLab-CAU/ComputerVision-2401#64]
I am writing to inquire about the specific reasons for the reduction in the number of parameters as discussed on page 65 of the lecture notes on Computer Vision.

In the lecture, it is mentioned that the number of parameters decreases significantly in certain convolutional neural network (CNN) architectures. I would like to understand this in more detail and see some specific examples of the reduction in parameter count.

Could you please elaborate on the following points regarding the reduction in the number of parameters?

![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92920482/bc3fc4df-fa40-4d76-ad7b-4c4ed5f26ecf)

1. Group Convolution: How does the use of group convolution contribute to the reduction in the number of parameters? Could you provide an example of how this is implemented and its impact on the overall network efficiency? Specifically, I would like to see a comparison of the number of parameters before and after applying group convolution.

2. Depthwise Convolution: The lecture notes mention depthwise convolution as a method to approximate standard convolution. How does this approach reduce the parameter count, and what are the trade-offs in terms of performance and accuracy? Again, a numerical example showing the reduction in the number of parameters would be very helpful.

**Comment by yjyoo3312** [comment]
@zxcv3296 Thank you for the comment! (and would you send your name by mail? yjyoo3312@cau.ac.kr)

Group convolution is an important technique for reducing the number of parameters in a convolutional neural network. By using N groups, group convolution approximates the standard convolution operation with N smaller convolutions, each having input and output channels equal to  C_in/N and C_out/N, respectively. Consequently, each smaller convolution has (1/N)^2 the parameters of a standard convolution. Since there are N such smaller convolutions, the total number of parameters is reduced to 1/N of the original.

Depthwise convolution is a special case where N=C_in. Therefore, the total reduction in parameters is 1/C_in. This method significantly reduces the number of parameters but does not mix information across channels, so it is usually combined with pointwise convolution (1x1 convolution).

Have a nice vacation!
