### ISSUE TITLE
[Lecture13][0619] About the role of reg layer in RPN

### ISSUE THREAD

**Issue by choigiheon** [PiLab-CAU/ComputerVision-2401#66]
<img width="563" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/118817112/c3dc9b36-d291-442f-a406-b0b54afde021">

I understand the role of the cls layer, but I don't understand the role of the reg layer. Since the anchor boxes predefined, isn't it enough to just determine whether object exists or not? If it is determined that an object exists, the RPN does give the corresponding region proposal. Otherwise it doesn't.

Does the reg layer adjust the values of the anchor boxes to more accurate region proposals, like R-CNN? If so, wouldn't this be redundant since the following Fast R-CNN also performs the same operation afterwards?

Thank you.

**Comment by yjyoo3312** [comment]
@choigiheon Thank you for the comment!

Yes, as you assumed, the regression layer predicts more accurate box proposals through bounding box regression. Although it may seem redundant, training a region proposal network without bounding box regression is challenging because anchor boxes alone cannot adequately capture the object region.

Have a nice vacation!
