### ISSUE TITLE
[Lecture11][0620] About Dropout for the inference stage

### ISSUE THREAD

**Issue by Kwonminjeong0** [PiLab-CAU/ComputerVision-2401#69]
![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92988028/09a32b7f-6a8a-4f29-b469-2073547b78eb)

On this Page, I couldn't understand what the statement "If applying it to inference stage as well, we can measure uncertainty of the prediction." means. 
I expect that there might be different results when applying dropout at the inference stage, but I don't know how to interpret such results in terms of uncertainty.

Could you please explain what is meant by the statement 'If applying it to the inference stage as well, we can measure uncertainty of the prediction' in the context of dropout? Thank you.

**Comment by yjyoo3312** [comment]
@Kwonminjeong0 Thank you for the comment!

I refer to this concept based on the paper [Dropout as a Bayesian Approximation: Representing Model Uncertainty in Deep Learning](https://arxiv.org/abs/1506.02142).

If we enable dropout during the inference stage and repeat the inference for the same input, our output results will vary due to changes in the fully connected (FC) layer where dropout is applied. If our input sample is relatively easy, we expect the output results to be consistent compared to when the input sample is difficult. We call the former case more certain and the latter more uncertain. This idea can be represented by a Bayesian structure, which exceeds the scope of an undergraduate course.

Have a nice vacation :)
